package com.eclipselink.analyzer;

import org.eclipse.persistence.sessions.Session;
import org.eclipse.persistence.sessions.DatabaseSession;
import org.eclipse.persistence.tools.schemaframework.SchemaManager;
import java.io.StringWriter;
import java.util.Date;

public class NativeDDLGenerator {
    public static String generate(Session session) {
        try {
            if (!(session instanceof DatabaseSession)) {
                return "-- Error: Session is not a DatabaseSession";
            }
            DatabaseSession dbSession = (DatabaseSession) session;
            SchemaManager schemaManager = new SchemaManager(dbSession);

            StringWriter writer = new StringWriter();
            schemaManager.outputDDLToWriter(writer);

            // Write a header
            writer.write("-- Generated by EclipseLink Native SchemaManager\n");
            writer.write("-- " + new Date() + "\n\n");

            // createDefaultTables(boolean) -> boolean usually means "create FKs"
            // We use a try-catch because it might fail to execute against the DB but still
            // write to the writer
            try {
                schemaManager.createDefaultTables(true);
            } catch (Exception e) {
                // Ignore DB execution errors, we only want the script
            }

            return writer.toString();
        } catch (Exception e) {
            return "-- Error generating native DDL: " + e.getMessage() + "\n";
        }
    }
}
